#!/bin/bash

case "$1" in
    -a | --all)     find . -maxdepth 1 \( -name "work*" -o -name "*.iso" -o -name "*-pkgs.txt" \) -exec sudo rm -r {} + ;;
    -w | --work)    find . -maxdepth 1 -name "work*" -exec sudo rm -r {} + ;;
    -i | --iso)     find . -maxdepth 1 \( -name "*.iso" -o -name "*-pkgs.txt" \) -exec rm {} + ;;
esac
