#!/bin/bash

case "$1" in
    -a | --all)     sudo rm -r $HOME/Documents/manjaro-awesome-respin/awesome/work*; sudo rm $HOME/Documents/manjaro-awesome-respin/awesome/*.iso; sudo rm $HOME/Documents/manjaro-awesome-respin/awesome/*-pkgs.txt ;;
    -w | --work)    sudo rm -r $HOME/Documents/manjaro-awesome-respin/awesome/work* ;;
    -i | --iso)     sudo rm $HOME/Documents/manjaro-awesome-respin/awesome/*.iso; sudo rm $HOME/Documents/manjaro-awesome-respin/awesome/*-pkgs.txt ;;
esac
