#!/bin/sh

if [ -n "$(blkid -L %MISO_LABEL% |grep -Eo 'sr|cd|loop')" ]; then
    echo -e " : \033[00;32m          _     _              _                   \033[0m"
    echo -e " : \033[00;32m         | |   | |            (_)                  \033[0m"
    echo -e " : \033[00;32m         | | _ | | ____ ____   _  ____  ____ ___   \033[0m"
    echo -e " : \033[00;32m         | || || |/ _  |  _ \ | |/ _  |/ ___) _ \  \033[0m"
    echo -e " : \033[00;32m         | || || ( ( | | | | || ( ( | | |  | |_| | \033[0m"
    echo -e " : \033[00;32m         |_||_||_|\_||_|_| |_|| |\_||_|_|   \___/  \033[0m"
    echo -e " : \033[00;32m                            (__/                   \033[0m"
    echo -e " : "
    echo -e " : "
    echo -e " : \033[33m Remove the boot medium, close the tray (if any), then press ENTER. \033[0m"
    echo -e " : "
    echo -e " : "
    echo -e ".:."

    read -t 120
fi
