#!/bin/bash
# update setup

# do UID checking here so someone can at least get usage instructions
if [ "$EUID" != "0" ]; then
    echo "error: This script must be run as root."
    exit 1
fi

# force to use english
export LANG=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8

if [ ! -e "/etc/manjaro" ] ; then
   echo "error: This script must be run on livecd."
fi

wget http://git.manjaro.org/core/manjaroiso/blobs/raw/master/configs/shared/overlay-livecd/etc/manjaro/update-setup-files -O /etc/manjaro/update-setup-files

echo "Cleaning framework..."
for file in $(cat /etc/manjaro/update-setup-files); do
    rm /etc/manjaro/$file

    echo "Downloading new framework..."
    wget http://git.manjaro.org/core/manjaroiso/blobs/raw/master/configs/shared/overlay-livecd/etc/manjaro/$file -O /etc/manjaro/$file
    chmod a+x /etc/manjaro/km
    chmod a+x /etc/manjaro/lg
    chmod a+x /etc/manjaro/livecd
    chmod a+x /etc/manjaro/setup
    chmod a+x /etc/manjaro/setup-0.8
    chmod a+x /etc/manjaro/setup-0.9
done

clear
echo "Update done. Start with 'sudo setup'"
