#!/bin/sh

INTERFACE=$1 # The interface which is brought up or down
STATUS=$2 # The new state of the interface

case "$STATUS" in
    'up') # $INTERFACE is up
	if [ -e "/tmp/mhwd.task" ]; then
		/usr/bin/pamac-refresh
	fi
	;;
esac
